import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const srcPath = join(__dirname, '../../web/src/lib/schema.ts')
const destPath = join(__dirname, '../src/schema.ts')

const src = readFileSync(srcPath, 'utf8')

// Skip leading comment block; copy shared slice up to the Plan catalog section
const startIdx = src.indexOf('\nexport ')
const cutIdx = src.indexOf('// ─── Plan catalog')
const shared = src
  .slice(startIdx >= 0 ? startIdx + 1 : 0, cutIdx >= 0 ? cutIdx : undefined)
  .trimEnd()

const banner = `// AUTO-GENERATED by scripts/sync-schema.mjs — do not edit.
// Source of truth: web/src/lib/schema.ts
`
writeFileSync(destPath, banner + '\n' + shared + '\n')
console.log('✓ cli/src/schema.ts synced from web/src/lib/schema.ts')
