// AUTO-GENERATED by scripts/sync-schema.mjs — do not edit.
// Source of truth: web/src/lib/schema.ts

export type Tool = 'claude-code' | 'codex' | 'cursor' | 'windsurf' | 'copilot' | 'gemini'

export type Tier = 'frontier' | 'strong' | 'fast'

export const TIER_RANK: Record<Tier, number> = { frontier: 3, strong: 2, fast: 1 }

export const WEEKS_PER_MONTH = 52 / 12  // 4.333…

export const AVG_TOKENS_PER_MESSAGE = 2000  // rough tokens per user+assistant turn
export const AVG_TOKENS_PER_REQ = 3000  // rough tokens per non-message request

// The top-level output of the CLI — pasted into the webpage
export interface UsageProfile {
  schemaVersion: 1;
  generatedAt: string;   // ISO-8601 datetime
  range: { from: string; to: string };  // ISO date strings, inclusive
  tools: ToolUsage[];
}

// One entry per AI coding tool detected or probed
export interface ToolUsage {
  tool: Tool;
  verdict: 'rich' | 'partial' | 'minimal' | 'manual';
  metrics: ToolMetrics | null;     // null when verdict === 'manual'
  manualPrompts?: ManualPrompt[];  // present when the user must fill numbers manually
}

// Aggregated usage counters for one tool over the requested date range
export interface ToolMetrics {
  sessions: number;
  messages: number;
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  cacheCreateTokens: number;
  byModel: Record<string, ModelMetrics>;
}

export type ModelMetrics = Pick<ToolMetrics,
  'messages' | 'inputTokens' | 'outputTokens' | 'cacheReadTokens' | 'cacheCreateTokens'>;

// A field the user must fill in manually (for server-side data)
export interface ManualPrompt {
  field: string;   // e.g. "cursor.premiumRequestsUsed"
  label: string;   // human-readable label shown in the webpage form
  hint: string;    // where to find this value (URL or instructions)
}
